### ISSUE TITLE
Logo image

### ISSUE THREAD

**Issue by gorazd** [RujutaP21/RujutaP21.github.io#1]
The logo image is not loading because of different letter L in the file name.
The link to logo.svg is not working because the file is Logo.svg.

I find it easer to always stick to lowercase for file names, folders and file extensions.

If you open the Developer Tools and the Network tab and reload the page, you will see the assets that were not downloaded in red.

Please mark this issue as closed once you fix it.

**Comment by RujutaP21** [comment]
Renamed logo file and expected result is obtained.
But I have one issue while inspecting following element in browser.
The code is working but cannot select in browser, is it because height is missing?
`         .container-header{
	margin-right: auto;
	margin-left: auto;
	padding-left: 15px;
	padding-right: 15px;
	width: 100%;
`

**Comment by gorazd** [comment]
The child element is floated to the right, remember how the parent of a floated element doesn't clear the float and is does not grow. 

You could use `overflow: hidden;` on the parent or even better use flexbox to align the nav to the right.

**Comment by RujutaP21** [comment]
Thank you. It works
