### ISSUE TITLE
Cannot center the child element

### ISSUE THREAD

**Issue by RujutaP21** [RujutaP21/RujutaP21.github.io#2]
https://github.com/RujutaP21/RujutaP21.github.io/blob/298bfa3ba09cbdb4ef48d9f54bb5260c3e35dd2e/css/style.css#L121

I have this border element with (100px x 100px)image as child element aligned in center.
So ideally, the size of element after padding and border-size should be 118px x 118px but when  inspected it shows 118px x 122px. 
Because of these image is not getting centered and I cannot figure out the problem.

```
.border{
	display: inline-block;
	border-radius: 50%;
	padding: 0.5em;
	border: 1px dashed #E98074;
	align-self: center;
}

.home-image{
	margin: 0;
	width: 100px;
	height: 100px;
	border-radius: 50%;
	padding: 0.5em;
	background-color: rgb(240, 224, 224);
}
```

**Comment by gorazd** [comment]
This happens because the image is an **inline** element.
Changing the display property to **block** will remove the extra space.

Here is an explanation of this behaviour:
https://stackoverflow.com/questions/31444891/mystery-white-space-underneath-image-tag/31445364#31445364
