### ISSUE TITLE
Need: Connecting contact form to Netlify domain

### ISSUE THREAD

**Issue by RujutaP21** [RujutaP21/RujutaP21.github.io#5]
@gorazd 
I need to connect to netlify domain to send email on submitting the contact form.

**Html file :** https://github.com/RujutaP21/RujutaP21.github.io/blob/f6b9c81e481f8e78040bdcc4c7c7fc67714e9f8e/contact.html#L52

**Php file :** https://github.com/RujutaP21/RujutaP21.github.io/blob/f6b9c81e481f8e78040bdcc4c7c7fc67714e9f8e/contact.php

**Comment by gorazd** [comment]
Here is how forms work on Netlify: https://docs.netlify.com/forms/setup/

You don't need PHP for this, PHP doesn't run on GitHub pages or Netlify.

**Comment by RujutaP21** [comment]
It is working.
Thank you
